name: "Dependency Submission"
on: [push, pull_request]
jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: gradle/actions/dependency-submission@dependency-submission-beta
